-- AlterTable
ALTER TABLE "DepartmentHead" ADD COLUMN     "photoFocusX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "photoFocusY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "photoZoom" INTEGER NOT NULL DEFAULT 100;

-- AlterTable
ALTER TABLE "DepartmentMember" ADD COLUMN     "photoFocusX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "photoFocusY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "photoZoom" INTEGER NOT NULL DEFAULT 100;
